globalvariable.WxVibeCodingDemos.PackageTestingSecretVar2.isSecure=true
globalvariable.WxVibeCodingDemos.PackageTestingSecretVar2.value=SECRET1
globalvariable.WxVibeCodingDemos.PackageTestingVar1.value=testing1